### PR TITLE
Revert Trolling

### PR DESCRIPTION
**Pull request by minkcrypto**
This reverts commit 05bd4a9d2782684cbbcec09141ffce22d58812c3.

We are not a scam coin, we have more than 9 exchanges available for trading https://www.coingecko.com/en/coins/cpuchain plus 817 discord community members https://discord.io/cpuchain.

I believe @cryptozeny has a bad faith on our coin however we are not interested in his trolling activity (he thinks our coin is a rival with his sugarchain).

Quick comparison between CPUchain vs Sugarchain

| Compare | CPUchain | Sugarchain |
| ---------- | ---------- | -------------|
| CoinMarketCap | Listed on CMC | Not listed |
| CoinGecko | Listed | Listed |
| Exchanges | Crex24 and 9 more | Only Altmarkets |
| Community | 900 including discord, twitter, and telegram | 200 only on twitter and telegram, no discord (they got banned for trolling) |

CPUchain is listed on CMC https://coinmarketcap.com/currencies/cpuchain/ while Sugarchain doesn't.

This PR re-adds support for CPUchain.

### CODE REVIEW

**Comment by nao20010128nao** [comment]
Ok, before reviewing your PR, please let know me the following:
- Who are you?
- Who is `streetcrypto7`, who added 7650fb94f6e00e1f8ce21b4ba3404474354e11f6

**Comment by minkcrypto** [comment]
1. I am a founder of CPUchain and a main developer of CPUchain proof) I've wrote the official bitcointalk post https://bitcointalk.org/index.php?topic=5161183.0 and I've released the github binary https://github.com/cpuchain/cpuchain/releases .
2. streetcrypto7 was our community developer and he has retired few months ago.
3. Since cryptozeny think he is a rival with us while it isn't, I've showed it as an example to help your understanding.

**Comment by nao20010128nao** [comment]
```
lmao fudders from other coins (sugarchain, lightbit, uraniumx?) are banned
```
Screenshot_2020-01-31-13-37-34

You banned me on Discord, right?

**Comment by joeland1** [comment]
I wouldn't really consider it trolling. Its they don't want to support a coin which they disagree with in behavior. You obviously cant handle competition, and go out of your way to hurt other people. This goes against many other people's better judgement, and as a result people don't want to be associated with your coin.

Joe's Lesson of the day: Karma's a bitch

**Comment by joeland1** [comment]
Also, you got the dev of THIS repo banned. Why should he/she even help you now?

**Comment by nao20010128nao** [comment]
Without apologize to Sugarchain devs and me, asking to adding the shit is impossible.     
[Added to the blacklist too.](https://github.com/nao20010128nao/WalletGenerator.net/blob/master/docs/COINS_WILL_NOT_BE_ADDED.md)

**Comment by nao20010128nao** [comment]
Don't forget, you are **TROLLING US**.     
I never forgive you.

**Pull request closed without merging**
